# Generated by Django 5.2.14 on 2026-05-28 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='offers.candidate')),
                ('technology_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='offers.technology')),
            ],
            options={
                'db_table': 'candidates_technologies',
            },
        ),
        migrations.CreateModel(
            name='OfferTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='offers.offer')),
                ('technology_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='offers.technology')),
            ],
            options={
                'db_table': 'offers_technologies',
            },
        ),
    ]
